name: Secure Pipeline

on:
  pull_request:
    branches:
      - main
      - dev
  schedule:
    # Scan de code elke week
    - cron: '0 0 * * 0'  # Elke zondag om middernacht
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Tests
      run: |
        python -m unittest discover

  security_checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: SAST Scan (Bandit)
      run: |
        pip install bandit
        bandit -r .

   dependabot:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Dependabot configuration
      run: |
        mkdir -p .github
        cat > .github/dependabot.yml <<EOF
        version: 2
        updates:
          - package-ecosystem: "pip"
            directory: "/"
            schedule:
              interval: "weekly"
            commit-message:
              prefix: "deps"
              include: "scope"
            open-pull-requests-limit: 10
        EOF
    - name: Run Dependabot
      uses: dependabot/fetch-metadata@v1